# Configuración general de la aplicación IoT Smart Farm
kafka.bootstrap.servers="localhost:9092"
# Directorio base para el almacenamiento temporal y tablas Delta
ruta-base = "./tmp/"
# Definición de los topics de Kafka para cada tipo de sensor
topics {
  temperature-humidity = "temperature_humidity"
  co2 = "co2"
  soil-moisture = "soil_moisture"
}
