# Configuración de Log4j para el proyecto IoT Farm Monitoring
# Establecemos el nivel raíz de log a WARN y lo enviamos a la consola
log4j.rootCategory=WARN, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.err
log4j.appender.console.layout=org.apache.log4j.PatternLayout
# Formato del mensaje: Fecha, Nivel, Clase: Mensaje
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# Configuración para silenciar logs de librerías externas que son demasiado ruidosos
log4j.logger.org.spark_project.jetty=OFF
log4j.logger.org.spark_project.jetty.util.component.AbstractLifeCycle=OFF
log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper=OFF
log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=OFF