global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spark'
    static_configs:
      - targets: ['localhost:9095']

  - job_name: 'spark-driver'
    scrape_interval: 10s
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: ['localhost:4040']
        labels:
          group: 'spark'
          instance: 'driver'

  - job_name: 'spark-worker'
    scrape_interval: 10s
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['localhost:8081']
        labels:
          group: 'spark'
          instance: 'worker'